config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {registrations: :registrations }
  resources :users, only: [:index, :show]

  get '/search' => 'users#search', :as => 'search_page'

  resources :friendships, only: [:show, :create, :destroy]
  resources :friend_requests, only: [:show, :create, :destroy]

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :post_likes, only: [:show, :create, :destroy]
  resources :comment_likes, only: [:show, :create, :destroy]
  get '/posts/:id/edit/delete/:image_id' => 'posts#delete_attachment', :as => 'delete_image'

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"  # mount Sidekiq::Web in your Rails app

  # MyApp::Application.routes.draw do
  # # get 'post_likes/create'
  # # get 'post_likes/destroy'
  # # get 'posts/index'
  # # get 'posts/show'
  # # get 'posts/edit'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CommentMethods

  belongs_to :user
  belongs_to :post

  has_many :post_likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_post
  before_action :set_comment_id, only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_back(fallback_location: root_path, notice: "Comment added successfully!!")
    else
      redirect_back(fallback_location: root_path, notice: @comment.errors.full_messages)
    end
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to posts_path, notice: "Comment updated succesfully!!"
  end

  def destroy
    @comment.destroy
    redirect_back(fallback_location: root_path, notice: "Comment deleted succesfully!!")
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_path, notice: "You are not authorized to perform this action!!" if @comment.nil?
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment_id
    @comment = @post.comments.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% post.comments.reverse.each do |comment|%>
<%next unless comment.id %>
  <p style="margin-bottom:0;">
    [<%= time_ago_in_words(comment.created_at)%>]
    <strong><%= comment.user.name %></strong>: <%= comment.body %>

    <% if current_user.comment_liked?(comment.id)%>
      <%= link_to "Unlike", comment_like_path(id: current_user.comment_liked?(comment.id)[1]), method: :DELETE%>
    <% else %>
      <%= link_to "Like", comment_likes_path(comment_like: {user_id: current_user.id, comment_id: comment.id}), method: :post%>
    <% end %>
    <%= link_to "#{comment.like_count[0]}", comment_like_path(comment)%>

    <% if comment.user == current_user%>
      | <%= link_to "Edit", edit_post_comment_path(id: comment.id, post_id: comment.post_id)%> | 
      <%= link_to "Delete", post_comment_path(comment.post, comment), method: :DELETE %> 
    <% end %>
  
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [post, post.comments.build] do |f| %>
<%= f.text_field :body, style:"width:85%;"%>
<div id="Comment_btn_id", style="float:right;">
<%= f.submit "Comment" ,class:"btn btn-outline-dark btn-sm"%>
</div>
<% end %>

<!--
<script type="text/javascript">
$('form').submit(function() {  
    var valuesToSubmit = $(this).serialize();
    $.ajax({
        type: "POST",
        url:    "/posts"            //"$(this).attr('action')", //sumbits it to the given url of the form
        data: valuesToSubmit,
        dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
    })
    return false; // prevents normal behaviour
});
</script>



<script type="text/javascript">
    $('#Comment_btn_id').click(function(){
       $.ajax({

        url: "/comments/create",
        type: "POST",
        data: {id: $('#Comment_btn_id').val()},
        dataType: ""
      });
    });
</script>


success: function(data) {
          alert('successfully');
        }
  -->

app/views/comments/edit.html.erb
<h1>Edit comments</h1>

<%= form_for [@post, @comment] do |f| %>
<%= f.text_field :body%>
<%= f.submit class:"btn btn-outline-dark btn-sm" %>
<% end %><br/>

<%= link_to "Back", posts_path, class:"btn btn-outline-dark btn-sm"%>