config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {registrations: :registrations }
  resources :users, only: [:index, :show]

  get '/search' => 'users#search', :as => 'search_page'

  resources :friendships, only: [:show, :create, :destroy]
  resources :friend_requests, only: [:show, :create, :destroy]

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :post_likes, only: [:show, :create, :destroy]
  resources :comment_likes, only: [:show, :create, :destroy]
  get '/posts/:id/edit/delete/:image_id' => 'posts#delete_attachment', :as => 'delete_image'

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"  # mount Sidekiq::Web in your Rails app

  # MyApp::Application.routes.draw do
  # # get 'post_likes/create'
  # # get 'post_likes/destroy'
  # # get 'posts/index'
  # # get 'posts/show'
  # # get 'posts/edit'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord  
  include UserMethods

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :friend_requests, dependent: :destroy
  has_many :req_received, through: :friend_requests

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy

  GENDER = ["Male", "Female", "Other"]
  validates :gender, inclusion: GENDER
  validates :username, :firstname, :lastname, :gender, :birthday, presence: true
  validates :username, uniqueness: true

  scope :search_user, -> (search) {where("lower(firstname) LIKE :search OR lower(lastname) LIKE :search OR lower(username) LIKE :search", search: "%#{search.downcase}%")}
  scope :registered_users, -> (id) {all.where.not(id: id)} 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.registered_users(current_user.id)
    @requests = current_user.requests_ids(current_user)
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    @search =  params[:search]
    if @search.blank?   
      redirect_back(fallback_location: root_path, notice: "Search field is empty!!")
    else
      @results = User.search_user(@search)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile_pic.html.erb
  <% if @user.profile_image.attached? %>
    <%= image_tag(@user.profile_image, atl: "profile image", style:"width:150px; height:auto;")%>
  <% else %>
    <%= image_tag ("unknown_user.jpg"), atl: "profile image", style:"width:150px; height:auto;"%>
  <% end %>

app/views/users/index.html.erb
<h1>Registered users list</h1>

<table class="table table-hover" style="text-align:center;">
  <thead class="thead-light">

    <tr>
      <th scope="col">#</th>
      <th scope="col"> Username </th>
      <th scope="col"> Name </th>
      <th scope="col"></th>
    </tr>

  </thead>

  <tbody>
    <% @users.each_with_index do |user,i|%>

      <tr>
        <td ><%= "#{i+1}"%></td>
        <td ><%= user.username%></td>
        <td ><%= user.name%></td>
        <td >
          <% if current_user.friend_ids.include?(user.id) %>
            <%= link_to "See profile", user_path(id: user.id), class:"btn btn-outline-dark btn-sm", style:"color:green;" %> | 
            <%= link_to "Unfriend", friendship_path(user), method: :DELETE, class:"btn btn-outline-dark btn-sm", style:"color:red;" %>
          
          <% else %>
            
            <% unless @requests.include?(user.id) %>
              <%= link_to "Add Friend", friend_requests_path(friend_request: {user_id: user.id, req_received_id: current_user.id}), method: :post, class:"btn btn-outline-dark btn-sm" %>
            <% else %>
              <%= link_to "Cancel Request", friend_request_path(user), method: :DELETE, class:"btn btn-outline-dark btn-sm", style:"color:red;" %>
            <% end %>
          
          <% end %>
        </td>
      </tr>

    <%end%>
  </tbody>
</table>

app/views/users/search.html.erb
<h3>Search Results</h3>  

<% unless @results.empty? %>
    <% @results.each do |result| %>

        <table>
            <tbody>
            <tr> <td style="margin:0;padding: 5px 20px;"> <%= result.name %></td> <tr>
            </tbody>
        </table>
    
    <% end %>

<% else %>
    <p>No match found!!</p>
    
<%end%>

app/views/users/show.html.erb
<div class="justify-content-center">
  <div class="row mb-4">
    <div class="col-12 text-center">
      <% if @user.id == current_user.id%>
        <h2>Your Profile</h2>
      <% else %>
        <h2><%= @user.firstname.capitalize + "'s"%> Profile</h2>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div  class="col-12 col-md-2 mt-3">
      <%= render "users/profile_pic"%>
    </div>

    <div class="col-12 col-md-3"> 
      <table>
        <tr>
          <td style="padding:5px 0;"><strong>Username: </strong></td>
          <td style="padding:0 10px;"><%= @user.username %></td>
        </tr>
        <tr>
          <td style="padding:5px 0;"><strong>Name: </strong></td>
          <td style="padding:0 10px;"><%= @user.name %></td>
        </tr>
        <tr>
          <td style="padding:5px 0;"><strong>Email: </strong></td>
          <td style="padding:0 10px;"><%= @user.email %></td>
        </tr>
        <tr>
          <td style="padding:5px 0;"><strong>Date of Birtday: </strong></td>
          <td style="padding:0 10px;"><%= @user.birthday.strftime("%d-%B-%Y") %></td>
        </tr>
        <tr>
          <td style="padding:5px 0;"><strong>Gender: </strong></td>
          <td style="padding:0 10px;"><%= @user.gender %></td>
        </tr>
      </table>
      <br/>

      <div>
        <p><%= link_to "Friends list", friendship_path(id: @user.id), class:"btn btn-outline-dark btn-sm"%> | 
            <%= link_to "Posts", post_path(id: @user.id), class:"btn btn-outline-dark btn-sm"%>
            <% if @user.id == current_user.id%> 
            | <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-outline-dark btn-sm"  %>
            <% end %>
        </p>
      </div>

    </div>
  </div>

</div>