config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {registrations: :registrations }
  resources :users, only: [:index, :show]

  get '/search' => 'users#search', :as => 'search_page'

  resources :friendships, only: [:show, :create, :destroy]
  resources :friend_requests, only: [:show, :create, :destroy]

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :post_likes, only: [:show, :create, :destroy]
  resources :comment_likes, only: [:show, :create, :destroy]
  get '/posts/:id/edit/delete/:image_id' => 'posts#delete_attachment', :as => 'delete_image'

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"  # mount Sidekiq::Web in your Rails app

  # MyApp::Application.routes.draw do
  # # get 'post_likes/create'
  # # get 'post_likes/destroy'
  # # get 'posts/index'
  # # get 'posts/show'
  # # get 'posts/edit'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  include PostMethods
  
  belongs_to :user
 
  has_many_attached :post_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy 

  scope :posts_for_home_page, -> (arr){ where(user_id: arr).order(created_at: :desc)}
  scope :posts_for_current_user, -> (id){where(user_id: id).order(created_at: :desc)}

  validate :post_content, :post_images_type

  private
  def post_content
    if !(post_images.attached?) && (text.blank?)
      errors.add(:post, "can't be blank")
    end
  end

  def post_images_type
    if post_images.attached? 
      post_images.each do |image|
        unless image.content_type.in?(%("image/jpg" "image/jpeg" "image/png"))
          errors.add(:post_images, "only JPEG or PNG files are allowed!!")
        end
      end
    end
    
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_post_id, only: [:edit, :update, :destroy, :delete_attachment]

  def index
    arr = current_user.friend_ids
    arr.push(current_user.id)
    @posts = Post.posts_for_home_page(arr)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.posts_for_current_user(@user.id)
  end

  def edit
  end

  def update
     @post.update(posts_params)
    redirect_to posts_path, notice: "Post updated successfully!!"
  end

  def create
    @post = Post.new(posts_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: "Post has been created successfully"
    else
      redirect_back(fallback_location: root_path, notice: @post.errors.full_messages[0])
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post has been deleted successfully"
  end

  def delete_attachment
    @post.post_images[params[:image_id].to_i].purge
    redirect_back(fallback_location: root_path)
  end

  private
  def posts_params
    params.require(:post).permit(:text, post_images:[] )
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path, notice: "You are not authorized to perform this action!!" if @post.nil?
  end

  def set_post_id
    @post =  Post.find(params[:id])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="form-group">
  <%= form_for :post do |f|%>
    <div class="row">
      <div class="col-12">
        <%= f.text_area :text, rows: 2, class:"form-control"%><br />
      </div>
    </div>
    
  <div class="row">
    <div class="col-12 col-md-10 mb-2">
      <%=f.file_field :post_images, multiple: true, class:"btn btn-outline-dark btn-sm"%>
    </div>
  
    <div class="col-12 col-md-2">
      <%= f.submit "Create Post", class:" form-control btn btn-outline-dark btn-sm"%>
    </div>
  </div>

  <% end %>
</div>

app/views/posts/_posts.html.erb
<% posts.each do |post|%><hr/>


<div class="row">
  <div class="col">
    <p><strong><%= post.user.name%></strong> <%="[ #{time_ago_in_words(post.created_at)} ago]"%></p>
  </div>
  
  <div class="col-2">
    <p style="text-align:right;margin:0;">
      <% if post.user == current_user%>
      <%= link_to "Edit", edit_post_path(post), class:"btn btn-outline-dark btn-sm"%> | 
      <%= link_to "Delete", post_path(post), method: :DELETE, class:"btn btn-outline-dark btn-sm" %>
      <% end %> </p>
  </div>
</div>

  <div style="overflow:visible;">
   <%= post.text%>
  </div>

  <div>
    <%post.post_images.each do |image|%>
      <%= image_tag(image, style:"width:auto;height:300px;padding:4px 2px;")%>
    <%end%>

    <div>
      <%= render partial: "post_likes/like_share_bar", locals: {post: post}%>
    </div>

    <div style="margin-top:20px; width:50%;">
      <%= render partial: "comments/form", locals: {post: post}%>
      <%= render partial: "comments/comments", locals: {post: post}%>
    </div>

  </div>

<%end%>

app/views/posts/edit.html.erb
<%= link_to "Back", :back, class:"btn btn-outline-dark btn-sm"%><br/><br/>

<h1>Edit Posts</h1>

<%= form_for @post do |f|%>

  <%= f.text_area :text, rows: 2, style: 'width:100%;padding-top:5px;'%><br />

  <%=f.file_field :post_images, multiple: true, style:"padding:0;", class:"btn btn-outline-dark btn-sm"%>

  <%= f.submit style:"float:right;", class:"btn btn-outline-dark btn-sm"%>

<% end %><br/>

<% image_id = 0%>
<%@post.post_images.each do |image|%>

  <%= image_tag(image, style:"width:300px;height:300px;padding:4px 2px;")%>
  <%= link_to "Delete", delete_image_path(id: @post.id, image_id: image_id), class:"btn btn-outline-dark btn-sm", style:"vertical-align: top;"%>
  <% image_id += 1 %>

<%end%>

app/views/posts/index.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-12">
      <div>
        <%= render "posts/form"%>
      </div><br/>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div>
        <%= render partial: "posts/posts", locals: {posts: @posts} %>
      </div>
    </div>
  </div>

</div>

app/views/posts/show.html.erb
<div>
  <% if @user.id == current_user.id%>
    <h2>Your Posts</h2>
  <% else %>
    <h2><%= @user.firstname.capitalize + "'s"%> Posts</h2>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col"></div>
    
    <div class="col-12" style="padding:5px 15px;">
      <%= render partial: "posts/posts", locals: {posts: @posts} %>
    </div>


    <div class="col"></div>
  </div>
</div><br /><br />