config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {registrations: :registrations }
  resources :users, only: [:index, :show]

  get '/search' => 'users#search', :as => 'search_page'

  resources :friendships, only: [:show, :create, :destroy]
  resources :friend_requests, only: [:show, :create, :destroy]

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :post_likes, only: [:show, :create, :destroy]
  resources :comment_likes, only: [:show, :create, :destroy]
  get '/posts/:id/edit/delete/:image_id' => 'posts#delete_attachment', :as => 'delete_image'

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"  # mount Sidekiq::Web in your Rails app

  # MyApp::Application.routes.draw do
  # # get 'post_likes/create'
  # # get 'post_likes/destroy'
  # # get 'posts/index'
  # # get 'posts/show'
  # # get 'posts/edit'
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include CommentMethods

  belongs_to :user
  belongs_to :post

  has_many :post_likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy

  validates :body, presence: true
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  include CommentMethods

  belongs_to :user
  belongs_to :comment
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :req_received, class_name: "User"

  validates_uniqueness_of :user_id, scope: :req_received_id
  validates :user_id, :req_received_id, presence: true

  after_create :send_mail_on_create_request

  def send_mail_on_create_request
    SendNotificationJob.set(wait: 1.minutes).perform_later(self, self.req_received)
    # FriendRequestMailer.new_friend_request_email(self, self.req_received).deliver_later(wait: 1.minutes)
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  include DestroyFriendReq
  
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates_uniqueness_of :user_id, scope: :friend_id, on: :create
  validates :user_id, :friend_id, presence: true
  
  after_create :destroy_friend_req

end

app/models/post.rb
class Post < ApplicationRecord
  include PostMethods
  
  belongs_to :user
 
  has_many_attached :post_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy 

  scope :posts_for_home_page, -> (arr){ where(user_id: arr).order(created_at: :desc)}
  scope :posts_for_current_user, -> (id){where(user_id: id).order(created_at: :desc)}

  validate :post_content, :post_images_type

  private
  def post_content
    if !(post_images.attached?) && (text.blank?)
      errors.add(:post, "can't be blank")
    end
  end

  def post_images_type
    if post_images.attached? 
      post_images.each do |image|
        unless image.content_type.in?(%("image/jpg" "image/jpeg" "image/png"))
          errors.add(:post_images, "only JPEG or PNG files are allowed!!")
        end
      end
    end
    
  end

end

app/models/post_like.rb
class PostLike < ApplicationRecord
  include PostMethods
  
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord  
  include UserMethods

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", dependent: :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :friend_requests, dependent: :destroy
  has_many :req_received, through: :friend_requests

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :comment_likes, dependent: :destroy

  GENDER = ["Male", "Female", "Other"]
  validates :gender, inclusion: GENDER
  validates :username, :firstname, :lastname, :gender, :birthday, presence: true
  validates :username, uniqueness: true

  scope :search_user, -> (search) {where("lower(firstname) LIKE :search OR lower(lastname) LIKE :search OR lower(username) LIKE :search", search: "%#{search.downcase}%")}
  scope :registered_users, -> (id) {all.where.not(id: id)} 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_post_id, only: [:edit, :update, :destroy, :delete_attachment]

  def index
    arr = current_user.friend_ids
    arr.push(current_user.id)
    @posts = Post.posts_for_home_page(arr)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.posts_for_current_user(@user.id)
  end

  def edit
  end

  def update
     @post.update(posts_params)
    redirect_to posts_path, notice: "Post updated successfully!!"
  end

  def create
    @post = Post.new(posts_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: "Post has been created successfully"
    else
      redirect_back(fallback_location: root_path, notice: @post.errors.full_messages[0])
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Post has been deleted successfully"
  end

  def delete_attachment
    @post.post_images[params[:image_id].to_i].purge
    redirect_back(fallback_location: root_path)
  end

  private
  def posts_params
    params.require(:post).permit(:text, post_images:[] )
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_path, notice: "You are not authorized to perform this action!!" if @post.nil?
  end

  def set_post_id
    @post =  Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.registered_users(current_user.id)
    @requests = current_user.requests_ids(current_user)
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    @search =  params[:search]
    if @search.blank?   
      redirect_back(fallback_location: root_path, notice: "Search field is empty!!")
    else
      @results = User.search_user(@search)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def full_name(user)
    "@" + user.firstname.capitalize
  end

end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= flash[:notice]%>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_header.html.erb
<div class=".container-fluid">

  <nav class="navbar navbar-expand-lg navbar-collapse navbar-dark bg-dark" style="background-color: #e3f2fd;">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to "Friends App", users_path, class:"navbar-brand"%>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", posts_path, class:"nav-link"%>
        </li>

        <li class="nav-item active">
          <%= link_to "Profile", user_path(current_user), class:"nav-link"%>
        </li>

        <li class="nav-item active">
          <%= link_to "Friend Requests", friend_request_path(current_user), class:"nav-link"%>
        </li>

        <li class="nav-item active">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link"%>
        </li>

        <% else %>
        <li class="nav-item active">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
        </li>

        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
        </li>

        <% end %>

        <li class="nav-item nav-link">
          <%= full_name(current_user) if user_signed_in?%>
        </li>
      
      </ul>

      <%= form_tag search_page_path, method: :GET, class:"form-inline my-2 my-lg-0" do %>
      <%= search_field_tag :search, params[:search], placeholder: "Search user", class:"form-control mr-sm-2"%>
      <%= button_tag "search", class:"btn btn-outline-success my-2 my-sm-0"%>
      <% end %>

    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Friend App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
    <%= render "layouts/header"%><br/>

    <div style="margin:0 30px 0 30px;">
      <% if !flash[:notice].blank?%>
        <%= render "layouts/alerts"%>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>